// poopy-birdy-os app service worker
// ----------------------------------
// Precaches the full web export so the installed PWA boots and plays
// offline after one successful online visit. Coexists with the
// cross-origin-isolation shim (coi-serviceworker.min.js) — that SW
// owns COOP/COEP header injection; this one owns the cache.
//
// This file is generated by game-v0.2/tools/build_web.sh from
// game-v0.2/tools/web_shell/sw.js.tmpl. Two placeholders (named
// APP_VERSION and PRECACHE_LIST, surrounded by double underscores
// in the template) are substituted at build time:
//   - the version is a 12-char SHA-256 over the build's file list,
//     stable per-build and changing whenever any artifact's bytes
//     change — gives us a clean cache key per build.
//   - the precache list is a JSON array of relative URLs (one per
//     file in build/web/, with sw.js itself excluded).

const CACHE_PREFIX = 'poopy-birdy-v';
const CACHE_NAME = CACHE_PREFIX + '60c5fff5a710';
const PRECACHE = ["./coi-serviceworker.min.js", "./icon-180.png", "./icon-192.png", "./icon-512.png", "./index.apple-touch-icon.png", "./index.audio.position.worklet.js", "./index.audio.worklet.js", "./index.html", "./index.icon.png", "./index.js", "./index.pck", "./index.png", "./index.wasm", "./manifest.webmanifest", "./splash.png"];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      // addAll is atomic: any fetch failure rejects the whole install
      // so we never persist a partial bundle.
      return cache.addAll(PRECACHE);
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (names) {
      return Promise.all(names.map(function (name) {
        // Only touch our own caches; leave anything without our prefix
        // alone (other origins / shared profile testing).
        if (name.indexOf(CACHE_PREFIX) === 0 && name !== CACHE_NAME) {
          return caches.delete(name);
        }
        return undefined;
      }));
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener('fetch', function (event) {
  // Only GETs are cacheable; pass everything else straight through.
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then(function (cached) {
      if (cached) return cached;
      return fetch(event.request);
    })
  );
});
